<?php

namespace MediaRatings\Models;

/**
 * MediaSeriesSeasonEpisodes
 * 
 * @package MediaRatings\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-03-30, 20:32:00
 */
class MediaSeriesSeasonEpisodes extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=20, nullable=false)
     */
    protected $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=20, nullable=false)
     */
    protected $external_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=20, nullable=false)
     */
    protected $season_id;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    protected $name;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $plot;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $air_date;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    protected $episode_number;

    /**
     *
     * @var string
     * @Column(type="string", length=512, nullable=true)
     */
    protected $still_path;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    protected $vote_count;

    /**
     *
     * @var double
     * @Column(type="double", length=4, nullable=true)
     */
    protected $vote_average;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field external_id
     *
     * @param integer $external_id
     * @return $this
     */
    public function setExternalId($external_id)
    {
        $this->external_id = $external_id;

        return $this;
    }

    /**
     * Method to set the value of field season_id
     *
     * @param integer $season_id
     * @return $this
     */
    public function setSeasonId($season_id)
    {
        $this->season_id = $season_id;

        return $this;
    }

    /**
     * Method to set the value of field name
     *
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Method to set the value of field plot
     *
     * @param string $plot
     * @return $this
     */
    public function setPlot($plot)
    {
        $this->plot = $plot;

        return $this;
    }

    /**
     * Method to set the value of field air_date
     *
     * @param string $air_date
     * @return $this
     */
    public function setAirDate($air_date)
    {
        $this->air_date = $air_date;

        return $this;
    }

    /**
     * Method to set the value of field episode_number
     *
     * @param integer $episode_number
     * @return $this
     */
    public function setEpisodeNumber($episode_number)
    {
        $this->episode_number = $episode_number;

        return $this;
    }

    /**
     * Method to set the value of field still_path
     *
     * @param string $still_path
     * @return $this
     */
    public function setStillPath($still_path)
    {
        $this->still_path = $still_path;

        return $this;
    }

    /**
     * Method to set the value of field vote_count
     *
     * @param integer $vote_count
     * @return $this
     */
    public function setVoteCount($vote_count)
    {
        $this->vote_count = $vote_count;

        return $this;
    }

    /**
     * Method to set the value of field vote_average
     *
     * @param double $vote_average
     * @return $this
     */
    public function setVoteAverage($vote_average)
    {
        $this->vote_average = $vote_average;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field external_id
     *
     * @return integer
     */
    public function getExternalId()
    {
        return $this->external_id;
    }

    /**
     * Returns the value of field season_id
     *
     * @return integer
     */
    public function getSeasonId()
    {
        return $this->season_id;
    }

    /**
     * Returns the value of field name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Returns the value of field plot
     *
     * @return string
     */
    public function getPlot()
    {
        return $this->plot;
    }

    /**
     * Returns the value of field air_date
     *
     * @return string
     */
    public function getAirDate()
    {
        return $this->air_date;
    }

    /**
     * Returns the value of field episode_number
     *
     * @return integer
     */
    public function getEpisodeNumber()
    {
        return $this->episode_number;
    }

    /**
     * Returns the value of field still_path
     *
     * @return string
     */
    public function getStillPath()
    {
        return $this->still_path;
    }

    /**
     * Returns the value of field vote_count
     *
     * @return integer
     */
    public function getVoteCount()
    {
        return $this->vote_count;
    }

    /**
     * Returns the value of field vote_average
     *
     * @return double
     */
    public function getVoteAverage()
    {
        return $this->vote_average;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("vokuro");
        $this->belongsTo('season_id', 'MediaRatings\Models\\MediaSeriesSeason', 'id', ['alias' => 'MediaSeriesSeason']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'media_series_season_episodes';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return MediaSeriesSeasonEpisodes[]|MediaSeriesSeasonEpisodes
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return MediaSeriesSeasonEpisodes
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
